### ISSUE TITLE
Add ability to view website styles in WYSIWYG editor

### ISSUE THREAD

**Issue by 1forh** [skycatchfire/fire#148]
ask brent what to do

**Comment by BrentWMiller** [comment]
# Modules
Install and enabled https://www.drupal.org/project/allowed_formats.

This module was added to our starter board so it should be in all new projects. The module allows you to limit fields to the certain text editors set up in `/admin/config/content/formats`.

<img width="943" alt="Screen Shot 2020-02-17 at 12 36 33 PM" src="https://user-images.githubusercontent.com/13574057/74675744-2feed100-5182-11ea-8dc4-f069a4188b5f.png">

Make sure you have a "Basic" and "Full" editor. The Full editor should have every option you would want to use in a description/copy field. Basic would be limited to things like bold, italic, etc. Check G4G for an examples of both of these.

<img width="1074" alt="Screen Shot 2020-02-17 at 12 33 06 PM" src="https://user-images.githubusercontent.com/13574057/74675486-adfea800-5181-11ea-99e7-01f453b79cb8.png">

Allow all roles to use both of them. We can set specifics on each field using `allowed_formats`.

<img width="939" alt="Screen Shot 2020-02-17 at 12 32 00 PM" src="https://user-images.githubusercontent.com/13574057/74675430-8a3b6200-5181-11ea-9b09-a7eb54013a1b.png">


# Code changes
In `fire.info.yml` add these lines so that CKEditor will load our bundled stylesheet:
```yml
ckeditor_stylesheets:
  - dist/bundle.css
```

In `_scaffolding.scss` change the body styles to the following so CKEditor won't just show white:
```scss
body {
  &.fire-page {
    opacity: 0;
  }

  &.has-loaded {
    opacity: 1;
  }
}
```

# CMS
Add **atomic classes only** to the full editor. Nothing should ever by section specific since these are global.

<img width="659" alt="Screen Shot 2020-02-17 at 12 34 32 PM" src="https://user-images.githubusercontent.com/13574057/74675655-fb7b1500-5181-11ea-8534-9664a320c887.png">

Here are the full editor options on G4G

<img width="1037" alt="Screen Shot 2020-02-17 at 12 39 07 PM" src="https://user-images.githubusercontent.com/13574057/74675854-88be6980-5182-11ea-9f0c-a24eb4440df0.png">

**Comment by BrentWMiller** [comment]
Codes changes made, need to do the rest in CMS when setting project up.
